stages:
  - test
  - lint
  - release

.python_test:
  stage: test
  script:
    - apt-get update
    - apt-get install -y ffmpeg
    - python runtests.py

head:
  extends: .python_test
  image: python:3.8
  before_script:
    - pip install .['testing']

lts_211:
  image: python:3.8
  extends: .python_test
  before_script:
    - pip install .['testing'] wagtail~=2.11 django~=3.1

lts_215:
  image: python:3.10
  extends: .python_test
  before_script:
    - pip install .['testing'] wagtail~=2.15 django~=4.0

flake8:
  stage: lint
  image: python:3.8
  before_script:
    - pip install flake8
  script:
    - flake8 wagtailvideos/ tests/

isort:
  stage: lint
  image: python:3.8
  before_script:
    - pip install isort -e .
  script:
    - isort --recursive --diff --check-only wagtailvideos/ tests/

build:
  image: python:3.8
  stage: release
  before_script:
    - pip install --upgrade setuptools wheel twine
  script:
    - ./setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - tags
